In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('Auto_vehicle.csv', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [3]:
df.shape
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [4]:
#add column names to dataframe
column_names= ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
df.columns
df.columns= column_names
df.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295

In [5]:
#data wrangling / data cleaning
df.replace("?", np.nan, inplace=True)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [6]:
#evaluate for mising data idnull() and notnull
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [7]:
#check data type of each column in data frame
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [8]:
#change the colun data type and replace null (NaN) values with appropriate values
avg_norm_loss= df["normalized-losses"].astype("float").mean()
avg_bore= df["bore"].astype("float").mean()
avg_stroke= df["stroke"].astype("float").mean()
avg_peak_rpm= df["peak-rpm"].astype("float").mean()
avg_horsepower= df["horsepower"].astype("float").mean()

print("average normal loss : ",avg_norm_loss)
print("average bore : ",avg_bore)
print("average stroke : ",avg_stroke)
print("average peak-rpm : ",avg_peak_rpm)
print("average horsepower : ",avg_horsepower)

average normal loss :  122.0
average bore :  3.3297512437810957
average stroke :  3.2554228855721337
average peak-rpm :  5125.369458128079
average horsepower :  104.25615763546799

In [9]:
#replace NaN values by mean
df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=True)
df["bore"].replace(np.nan, avg_bore, inplace=True)
df["stroke"].replace(np.nan, avg_stroke, inplace=True)
df["peak-rpm"].replace(np.nan, avg_peak_rpm, inplace=True)
df["horsepower"].replace(np.nan, avg_horsepower, inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
#replace num-of-doors nan values using frequency
df["num-of-doors"].value_counts()
df["num-of-doors"].replace(np.nan, "four", inplace=True)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [11]:
#cleaning NaN values in price column
# that column is the impotent column beacuse that is we will use to prediction value in our model. so we need to drop every row when 
# price column has NaN value

df.dropna(subset=["price"], axis=0, inplace=True)

#reset left hand side indises, beacuse we droped two rows
df.reset_index(drop=True, inplace=True)
df.head()

df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [12]:
df.dtypes
#need to convert data types to proper format

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [13]:
df[["bore","stroke","peak-rpm","price"]]= df[["bore","stroke","peak-rpm","price"]].astype("float")
df[["normalized-losses"]]= df[["normalized-losses"]].astype("int")
df.dtypes
df.to_csv("cleaned_Auto_vehicle.csv", index=False)

In [14]:
#  (Standardization, Normalization, Binning, Dummy Variable)

#load clean dataset
df= pd.read_csv("cleaned_Auto_vehicle.csv")
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [15]:
# data Standardization : Standardization is the process of transforming data into a common format which allows the researcher to make the meaningful comparison.
#in my data frame city-mpg and highway-mpg present in miles per galum. but we want liters per 100 km we need to unit convertion

#1 Gallon = 3.785 Liter, 1 Mile = 1.609 Kilometer, L/1 km = 3.785/1,609 = 2.35 mpg, L/100km = 2.35*100 = 235

#convert mpg to L/100km by mathematical operation(235 devided by mpg)
df["highway-L/100km"]= (235/df["highway-mpg"])
df["city-L/100km"]= (235/df["city-mpg"])
df.head()
df.dtypes[["highway-L/100km","city-L/100km"]]

highway-L/100km    float64
city-L/100km       float64
dtype: object

In [16]:
#Normalized data: Some data column spred big range. so we nedd to normalize that column into 0 to 1 range
#replace original value by (original value)/(maximum value)
df[["length","width","height"]].head()

   length  width  height
0   168.8   64.1    48.8
1   168.8   64.1    48.8
2   171.2   65.5    52.4
3   176.6   66.2    54.3
4   176.6   66.4    54.3

In [17]:
df["length"]= df["length"]/df["length"].max()
df["width"]= df["width"]/df["width"].max()
df["height"]= df["height"]/df["height"].max()
df[["length","width","height"]].head()

     length     width    height
0  0.811148  0.890278  0.816054
1  0.811148  0.890278  0.816054
2  0.822681  0.909722  0.876254
3  0.848630  0.919444  0.908027
4  0.848630  0.922222  0.908027

In [18]:
#Binning technique
#you know vehicle price range depend on housepower low, medium and high. so no need to each and every vehical exact house power 
#beacuse of that we need to conver housepower into 3 different category we called it binnning. in dataframe max is 262 and min : 48

#we will use the pandas method 'cut' to segment housepower column into 3 bins

# 3 bins of equal size bandwidth so we use numpy's linspace(start value, end value, numbers generated) function

#we are building 3 bins of equal length, there should be 4 dividers. so numbers_generated=4

bins= np.linspace(df["horsepower"].min(), df["horsepower"].max(), 4)
bins

array([ 48.        , 119.33333333, 190.66666667, 262.        ])

In [19]:
#set the group names
group_names= ["low","medium","high"]

#apply pandas cut method determine each value of df["horsepower"] belogs to
df["horsepower-binned"]= pd.cut(df["horsepower"], bins, labels=group_names, include_lowest=True)
df[["horsepower","horsepower-binned"]].head(20)

    horsepower horsepower-binned
0        111.0               low
1        111.0               low
2        154.0            medium
3        102.0               low
4        115.0               low
5        110.0               low
6        110.0               low
7        110.0               low
8        140.0            medium
9        101.0               low
10       101.0               low
11       121.0            medium
12       121.0            medium
13       121.0            medium
14       182.0            medium
15       182.0            medium
16       182.0            medium
17        48.0               low
18        70.0               low
19        70.0               low

In [20]:
#see value count for each type
df["horsepower-binned"].value_counts()

low       153
medium     43
high        5
Name: horsepower-binned, dtype: int64

In [21]:
import matplotlib as plt
from matplotlib import pyplot

group_names=["low","medium","high"]
pyplot.bar(group_names, df["horsepower-binned"].value_counts())

#set x and y labels and plot title
plt.pyplot.xlabel("hoursepower")
plt.pyplot.ylabel("count")
plt.pyplot.title("hoursepower bins")

Text(0.5, 1.0, 'hoursepower bins')

In [22]:
#indicator varibles/ dummy variables 

#our target is liner regression model for that we need to that categorical varibles. so some cotegorical varibles ("labled : ex medium,low, high, fuel-type : gas , diesel) we need to conver numbers
#that are called ''dummy' because the numbers themselves don't have inherent meaning

# exaple : in this dataset fuel-type has two values that is "gas" and "diesel" only. but in regression model they dont understand the word for that 
# we need to use numbers for fuel-type. so need to convert fuel-type into indicator varibles

#for create dummy varibles we use pandas "get_dummies" method to assign numerical values of different category of fuel-types

df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price', 'highway-L/100km', 'city-L/100km',
       'horsepower-binned'],
      dtype='object')

In [23]:
df.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,highway-L/100km,city-L/100km,horsepower-binned
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111.0,5000.0,21,27,13495.0,8.703704,11.190476,low
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111.0,5000.0,21,27,16500.0,8.703704,11.190476,low
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154.0,5000.0,19,26,16500.0,9.038462,12.368421,medium
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.40,10.0,102.0,5500.0,24,30,13950.0,7.833333,9.791667,low
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.40,8.0,115.0,5500.0,18,22,17450.0,10.681818,13.055556,low
5,2,122,audi,gas,std,two,sedan,fwd,front,99.8,...,3.40,8.5,110.0,5500.0,19,25,15250.0,9.400000,12.368421,low
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,3.40,8.5,110.0,5500.0,19,25,17710.0,9.400000,12.368421,low
7,1,122,audi,gas,std,four,wagon,fwd,front,105.8,...,3.40,8.5,110.0,5500.0,19,25,18920.0,9.400000,12.368421,low
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.40,8.3,140.0,5500.0,17,20,23875.0,11.750000,13.823529,medium
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,2.80,8.8,101.0,5800.0,23,29,16430.0,8.103448,10.217391,low
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,2.80,8.8,101.0,5800.0,23,29,16925.0,8.103448,10.217391,low
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,3.19,9.0,121.0,4250.0,21,28,20970.0,8.392857,11.190476,medium
12,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,3.19,9.0,121.0,4250.0,21,28,21105.0,8.392857,11.190476,medium
13,1,122,bmw,gas,std,four,sedan,rwd,front,103.5,...,3.19,9.0,121.0,4250.0,20,25,24565.0,9.400000,11.750000,medium
14,0,122,bmw,gas,std,four,sedan,rwd,front,103.5,...,3.39,8.0,182.0,5400.0,16,22,30760.0,10.681818,14.687500,medium
15,0,122,bmw,gas,std,two,sedan,rwd,front,103.5,...,3.39,8.0,182.0,5400.0,16,22,41315.0,10.681818,14.687500,medium
16,0,122,bmw,gas,std,four,sedan,rwd,front,110.0,...,3.39,8.0,182.0,5400.0,15,20,36880.0,11.750000,15.666667,medium
17,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,3.03,9.5,48.0,5100.0,47,53,5151.0,4.433962,5.000000,low
18,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,3.11,9.6,70.0,5400.0,38,43,6295.0,5.465116,6.184211,low
19,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,3.11,9.6,70.0,5400.0,38,43,6575.0,5.465116,6.184211,low

In [24]:
dummy_variable_1= pd.get_dummies(df["fuel-type"])
dummy_variable_1.head(20)

    diesel  gas
0        0    1
1        0    1
2        0    1
3        0    1
4        0    1
5        0    1
6        0    1
7        0    1
8        0    1
9        0    1
10       0    1
11       0    1
12       0    1
13       0    1
14       0    1
15       0    1
16       0    1
17       0    1
18       0    1
19       0    1

In [25]:
#see fuel type value_counts()
df["fuel-type"].value_counts()

gas       181
diesel     20
Name: fuel-type, dtype: int64

In [26]:
#rename dummy_varible_1 data frame coumn names
dummy_variable_1.rename(columns={"gas": "fuel-type-gas", "diesel": "fuel-type-diesel"}, inplace=True)
dummy_variable_1.head(20)

    fuel-type-diesel  fuel-type-gas
0                  0              1
1                  0              1
2                  0              1
3                  0              1
4                  0              1
5                  0              1
6                  0              1
7                  0              1
8                  0              1
9                  0              1
10                 0              1
11                 0              1
12                 0              1
13                 0              1
14                 0              1
15                 0              1
16                 0              1
17                 0              1
18                 0              1
19                 0              1

In [27]:
#you know dummy_variables_1 dataframe is a temporary separate dataframe so we need to merge that into our main df dataframe

df= pd.concat([df, dummy_variable_1], axis=1) #axis=1 mean that dataframe add column wise
df.drop("fuel-type", axis=1, inplace=True) #drop original fuel type column
df.head(20)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,horsepower,peak-rpm,city-mpg,highway-mpg,price,highway-L/100km,city-L/100km,horsepower-binned,fuel-type-diesel,fuel-type-gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,111.0,5000.0,21,27,13495.0,8.703704,11.190476,low,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,111.0,5000.0,21,27,16500.0,8.703704,11.190476,low,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,154.0,5000.0,19,26,16500.0,9.038462,12.368421,medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,102.0,5500.0,24,30,13950.0,7.833333,9.791667,low,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,115.0,5500.0,18,22,17450.0,10.681818,13.055556,low,0,1
5,2,122,audi,std,two,sedan,fwd,front,99.8,0.851994,...,110.0,5500.0,19,25,15250.0,9.400000,12.368421,low,0,1
6,1,158,audi,std,four,sedan,fwd,front,105.8,0.925997,...,110.0,5500.0,19,25,17710.0,9.400000,12.368421,low,0,1
7,1,122,audi,std,four,wagon,fwd,front,105.8,0.925997,...,110.0,5500.0,19,25,18920.0,9.400000,12.368421,low,0,1
8,1,158,audi,turbo,four,sedan,fwd,front,105.8,0.925997,...,140.0,5500.0,17,20,23875.0,11.750000,13.823529,medium,0,1
9,2,192,bmw,std,two,sedan,rwd,front,101.2,0.849592,...,101.0,5800.0,23,29,16430.0,8.103448,10.217391,low,0,1
10,0,192,bmw,std,four,sedan,rwd,front,101.2,0.849592,...,101.0,5800.0,23,29,16925.0,8.103448,10.217391,low,0,1
11,0,188,bmw,std,two,sedan,rwd,front,101.2,0.849592,...,121.0,4250.0,21,28,20970.0,8.392857,11.190476,medium,0,1
12,0,188,bmw,std,four,sedan,rwd,front,101.2,0.849592,...,121.0,4250.0,21,28,21105.0,8.392857,11.190476,medium,0,1
13,1,122,bmw,std,four,sedan,rwd,front,103.5,0.908217,...,121.0,4250.0,20,25,24565.0,9.400000,11.750000,medium,0,1
14,0,122,bmw,std,four,sedan,rwd,front,103.5,0.908217,...,182.0,5400.0,16,22,30760.0,10.681818,14.687500,medium,0,1
15,0,122,bmw,std,two,sedan,rwd,front,103.5,0.931283,...,182.0,5400.0,16,22,41315.0,10.681818,14.687500,medium,0,1
16,0,122,bmw,std,four,sedan,rwd,front,110.0,0.946660,...,182.0,5400.0,15,20,36880.0,11.750000,15.666667,medium,0,1
17,2,121,chevrolet,std,two,hatchback,fwd,front,88.4,0.678039,...,48.0,5100.0,47,53,5151.0,4.433962,5.000000,low,0,1
18,1,98,chevrolet,std,two,hatchback,fwd,front,94.5,0.749159,...,70.0,5400.0,38,43,6295.0,5.465116,6.184211,low,0,1
19,0,81,chevrolet,std,four,sedan,fwd,front,94.5,0.763095,...,70.0,5400.0,38,43,6575.0,5.465116,6.184211,low,0,1

In [28]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price',
       'highway-L/100km', 'city-L/100km', 'horsepower-binned',
       'fuel-type-diesel', 'fuel-type-gas'],
      dtype='object')

In [29]:
df.to_csv("preprocessed   ( cleaned, Standardization, Normalization, Binning, Dummy Variable).csv", index=False)